import{i as u,S as m}from"./assets/vendor-7659544d.js";(function(){const e=document.createElement("link").relList;if(e&&e.supports&&e.supports("modulepreload"))return;for(const t of document.querySelectorAll('link[rel="modulepreload"]'))i(t);new MutationObserver(t=>{for(const s of t)if(s.type==="childList")for(const a of s.addedNodes)a.tagName==="LINK"&&a.rel==="modulepreload"&&i(a)}).observe(document,{childList:!0,subtree:!0});function r(t){const s={};return t.integrity&&(s.integrity=t.integrity),t.referrerPolicy&&(s.referrerPolicy=t.referrerPolicy),t.crossOrigin==="use-credentials"?s.credentials="include":t.crossOrigin==="anonymous"?s.credentials="omit":s.credentials="same-origin",s}function i(t){if(t.ep)return;t.ep=!0;const s=r(t);fetch(t.href,s)}})();const p="42651463-7e9bc4d6a898bed570bd4622e",f="https://pixabay.com/api/",n=document.querySelector(".loader");function d(o){const e=new URLSearchParams({key:p,q:o,image_type:"photo",orientation:"horizontal",safesearch:!0});return n.style.display="block",fetch(`${f}?${e}`).then(r=>{if(!r.ok)throw new Error("Network response was not OK");return r.json()}).then(r=>(n.style.display="none",r.hits.length===0&&u.error({fontSize:"large",close:!1,position:"topRight",messageColor:"white",timeout:2e3,backgroundColor:"red",message:"Sorry, there are no images matching your search query. Please try again!"}),r)).catch(r=>{console.log(r)})}function g(o){return o.hits.map(e=>`<div class="gallery-item">
      <a class="gallery-link" href="${e.largeImageURL}">
          <img class="gallery-image" src="${e.webformatURL}" alt="${e.tags}">
      </a>
      <div class="gallery-image-info">
          <p class="image-info-item"><span class="items-text">Likes: </span>${e.likes}</p>
          <p class="image-info-item"><span class="items-text">Views: </span>${e.views}</p>
          <p class="image-info-item"><span class="items-text">Comments: </span>${e.comments}</p>
          <p class="image-info-item"><span class="items-text">Downloads: </span>${e.downloads}</p>
      </div>
  </div>`).join("")}const y=document.querySelector(".search-form"),c=document.querySelector(".gallery"),h=new m(".gallery-link",{captions:!0,captionsData:"alt",captionDelay:200});let l="";y.addEventListener("submit",b);function b(o){o.preventDefault(),c.innerHTML="",l=o.target.elements.query.value.trim(),d(l).then(e=>{const r=g(e);c.insertAdjacentHTML("beforeend",r),h.refresh()}).catch(e=>console.log(e))}
//# sourceMappingURL=commonHelpers.js.map
